---
title: "source-code"
output: html_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(wordcloud)
library(shiny)
library(shinythemes)

#### How has renewable production has changed over time

#Get the data for year by year production of renewable energy
year_by_year <- read.csv("yearbyyear.csv")

#Rename columns for clearer interpretation
names(year_by_year) <- c("Year","Hydro","Biofuel", "Solar", "Geothermal")

### Is there a relationship between total energy consumption and renewable energy production

renewable_by_country <- read.csv("countrygeneration.csv")
consumption_by_country <-read.csv("countryconsumption.csv")

# This next block of code is focusing on areas of interest (country and total renewable energy produced)

renewable_by_country <- rename(renewable_by_country, "Total Renewable Energy Produced" = "Total..TWh.")
renewable_by_country <- select(renewable_by_country, c("Country", "Total Renewable Energy Produced"))

# the renewablecountry data is from 2017, so we'll just focus on consumption from 2017

consumption_by_country <- filter(consumption_by_country, Year == 2017)

#Configure a data frame with countries and numeric consumption (instead of strings)

Country <- colnames(consumption_by_country) [-1]
Consumption <- as.numeric(consumption_by_country) [-1]
consumption_by_country <- data.frame(Country, Consumption)

# now we want to merge these together into one table by country

con_prod_country <- merge (consumptionbycountry, renewablebycountry, by="Country")
con_prod_country_no <- filter(CountryRel, Country != "China")
```

```{r}

ui <- fluidPage(
  theme = shinytheme("superhero"),
  navbarPage("Exploring Renewable Energy Production",
  tabPanel("Overview", 
      titlePanel(h3("Exploring Renewable Energy Production", align = "center")),
      fluidRow(
         column(width=2),
         column(
           h6(p("This interactive R Shiny app is intended to help you visualize and understand developments in renewable energy")),
           width=8
         ),
         column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(plotOutput("cloud_production"), width = 8),
        column(width=2)
        ),
      fluidRow(
         column(width=2),
         column(
           h6(p("In the word cloud above, see the top twenty producers of renewable energy. The size of each country's name directly corresponds to the quanitity of renewable energy they produced in 2017.")),
           width=8
         ),
         column(width=2)
      )
  ),
  tabPanel("Composition", 
      titlePanel(h3("Composition of Renewable Energy Production", align = "center")),
      fluidRow(
         column(width=2),
         column(
           h4("How has the composition of renewable energy changed over time?", align = "center"),
           h6(p("Use the slider the adjust the year. The bar and pie charts below will display the composition of renewable energy production for this given year. Note how this composition changes from year to year. To recognize trends in composition over time, see the stacked chart below, which will show the renewable energy production from 1997 until the year you select")),
           width=8
         ),
         column(width=2)
      ),
      fluidRow(
        column(width=1),
        column(
          sidebarLayout(position = "left",
                        sidebarPanel(
                          "Year",
                          sliderInput(inputId = "year", 
                                      label = "Slide to adjust the year", 
                                      sep = "",
                                      value = 2015, min = 1997, max = 2017
                                      ),
                          ),
                        mainPanel(
                          tabsetPanel(
                            tabPanel("Bar", plotOutput("bar_composition")),
                            tabPanel("Pie", plotOutput("pie_composition")),
                            tabPanel("Stacked since 1990", plotOutput("stacked_composition"))
                          )
                        )
          ), 
          width = 10
        ),
        column(width=1)
      ),

      fluidRow(
         column(width=2),
         column(
           h6(p("By using the slider to manipulate these visualizations, you should begin to understand the developments in renewable energy production over time. The trends illustrated here lay the groundwork for further inquiry, such as how government support / intervention has supported these developments.")),
           width=8
         ),
         column(width=2)
      )
  ),
  tabPanel("Consumption and Production",
      titlePanel(h3("Renewable Energy Production & Total Energy Consumption", align = "center")),
      fluidRow(
         column(width=2),
         column(
           h4("Is there a relationship between total energy consumption and renewable energy production?", align = "center"),
           h6(p("The first scatterplot below highlights China in red, a clear outlier in both total energy consumption and renewable energy production. In order to focus on the relationship between these two variables, we will acknowledge China as an outlier and focus on the remaining countries")),
           width=8
         ),
         column(width=2)
      ),
      fluidRow(
         column(width=2),
         column(
           plotOutput("scatterfull", click = "scatter_click"),
           verbatimTextOutput("scatter_info"),
           width=8
         ),
         column(width=2)
      ),
      fluidRow(
         column(width=2),
         column(
           h6(p("After removing China, we can visualize the relationship between total energy consumption and renewable energy production. Note how certain countries seem to produce more renewable energy than expected (high renewable energy production with relatively low total energy consumption). Click on any point to see which country that point represents. Country names will display under the scatterplot")),
           width=8
         ),
         column(width=2)
      ),
      fluidRow(
         column(width=2),
         column(
           plotOutput("no_outliers", click = "no_click"),
           verbatimTextOutput("no_info"),
           width=8
         ),
         column(width=2)
      )
      ),
  tabPanel("Basic Documentation",
      fluidRow(
        column(width=2),
        column(
          h2("Project Documentation", align="center"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          h4("Project Purpose", align="center"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("     The overarching purpose of this project is to provide users with meaningful visualizations so that they can understand the development of renewable energy production over time and across the globe. While this project will not crease an exhaustive resource for understanding renewable energy production, I do intend it to enhance viewers' background understanding and lay the foundations for further inquiry. Furthermore, I hope these visualizations can present the developments in such a way that users begin to recognize patterns which coincide with historical and current events defining the renewable energy sector over the past twenty years."),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          h4("Data Description", align="center"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("     These visualizations are based on data from multiple datasets, which work effectively together to help achieve the purpose defined above."),
          width=8
          ),
        column(width=2)
      ), 
      fluidRow(
        column(width=2),
        column(
          p("(1)	renewablesPowerGeneration97-17 contains the production of renewable energy over the twenty years between 1997 and 2017. Furthermore, it specifies how much of this energy was from hydro, solar & geothermal. Each row represents a single observation (year) and each column represents a single attribute"),
          width=8
          ),
        column(width=2)
      ),
      
      fluidRow(
        column(width=2),
        column(
          p("(2)	top20CountriesPowerGeneration contains the data from 2017 of each of the top 20 countries’ renewable energy generation. Each row is a single observation (country) and each column represents a single attribute."),
          width=8
          ),
        column(width=2)
      ),
      
      fluidRow(
        column(width=2),
        column(
          p("(3)	Country_Consumption_TWH 2 has the total energy consumption for each year, broken up by country. Each row is an observation (year) and each column is a country. Thus, the cells represent the energy consumed by that country each year."),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          h4("Data Collection", align="center"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("This data was found on Kaggle; however, it was originally collected by and sourced from: Nature-Inspired Optimization Algorithms for Renewable Energy Generation, Distribution and Management—A Comprehensive Review by Vamsi Krishna Reddy Aala Kalananda and Venkata Lakshmi Narayana Komanapalli from Intelligent Paradigms for Smart Grid and Renewable Energy Systems. - 2021. Springer"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          h4("Users of the Visualization", align="center"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("This visualization is intended for a general audience of university students interested in renewable energy development and policy. The information conveyed via this visualization will help to provide these students with perspective, insights, and curiosity for their studies."),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          h4("Questions to Answer", align="center"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("The questions to outline are included on each section; however, they are also included here for complete documentation:"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("(1) How has the composition of renewable energy production changed over time? What trends have defined these changes?"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("(2) Is there a relationship between total energy consumption and renewable energy production?"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          h4("Insights from Data", align="center"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("(1) Over the two decades represented by this data, total production of renewable energy grew significantly. Within this growth, we can see a significant expansion in energy sources like solar and geothermal energy which represented a tiny portion of total renewable energy in 1997 and now represent a substantial proportion of total renewable energy production."),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("(2) There is a loose positive relationship between total energy consumption and renewable energy production. Obvious outliers to this rule include Brazil and Canada, who produce high amounts of renewable energy relative to their total energy consumption, and Iran, who produces less than expected."),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          h4("Improvements", align="center"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("Although this visualization establishes a strong basis for understanding recent developments in renewable energy policy, there is significant room for further improvements in future work / visualizations:"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("(1) This visualization fails to provide significant context for the trends in renewable energy composition. Instead, users are left to view the trends and hypothesize how these came to be. Future studies may incorporate relevant current / historical events as appropriate. Enerdata created a visualization in regards to energy consumption and the pandemic that included specific contextual points. Additional visualizations may draw inspiration from this work."),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("(2) The limitations of these datasets fail to illustrate these trends over longer periods of time or in recent years. Future visualizations could incorporate more comprehensive data"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("(3) To better understand the impact of government action on renewable energy, future apps could group countries in the scatterplots by government policies / actions"),
          width=8
          ),
        column(width=2)
      ),
      fluidRow(
        column(width=2),
        column(
          p("(4) Stronger UI design in more flexible frameworks, such as React, would allow for better interactivity / reactivity and thus a more presentable UI"),
          width=8
          ),
        column(width=2)
      )
  )
)
)

server <- function(input, output) {
  output$cloud_production <- renderPlot({
    wordcloud(
      words=renewablebycountry$Country, 
      freq = renewablebycountry$total, 
      colors=brewer.pal(8, "Dark2"), 
      scale=c(8,0.75)
    )
  })
  
  output$bar_composition <- renderPlot({
    #filter the data to only include data from this year (specified by slider)
    cur_year <- filter(year_by_year, Year == input$year)
    #Pivot the data longer, so we have one row of data representing each renewable energy source this year
    cur_year_long <- cur_year %>%
      pivot_longer(-"Year", names_to = "variable", values_to = "value")
    #Order the types appropriately
    cur_year_long$variable <- factor(cur_year_long$variable, levels = c("Hydro", "Biofuel", "Geothermal", "Solar"))
    #Create the bar plot
    ggplot(cur_year_long, aes(variable, value, fill = variable)) + 
      geom_bar(stat="identity") +
      scale_fill_brewer(palette="Accent") + 
      labs(title=paste("Composition of renewable energy production in", input$year, sep=" "),
        x = "Renewable Energy Source", y = "Renewable Energy Production (TWh)") + 
      theme(legend.position = "none")
  })
  
  output$pie_composition <- renderPlot({
    # filter the data to only include data from this year (specified by slider)
    cur_year <- filter(year_by_year, Year == input$year)
    # pivot the data longer, so we have one row of data representing each renewable energy source this year
    cur_year_long <- cur_year %>%
      pivot_longer(-"Year", names_to = "variable", values_to = "value")
    # order the types appropriately
    cur_year_long$variable <- factor(cur_year_long$variable, levels = c("Hydro", "Biofuel", "Geothermal", "Solar"))
    # ggplot technique - referenced https://www.r-graph-gallery.com/piechart-ggplot2.html
    ggplot(cur_year_long, aes(x="", y=value, fill=variable)) +
      geom_bar(stat="identity", width=1, color="white") +
      coord_polar("y", start=0) +
      labs(title=paste("Composition of renewable energy production in", input$year, sep=" "),
        x = "", y = "") +
      scale_fill_brewer(palette="Accent") + 
      theme(legend.position = "right") +
      guides(fill=guide_legend(title="Renewable Energy Source"))
    })
  
    output$stacked_composition <- renderPlot({
    #filter the data to only include data from 1997 (earliest date in the data) until value
    rel_years <- filter(year_by_year, Year <= input$year)
    # pivot the data longer, so we have one row of data representing each renewable energy source this year
    rel_years_long <- rel_years %>%
      pivot_longer(-"Year", names_to = "variable", values_to = "value")
    # order the types appropriately
    rel_years_long$variable <- factor(rel_years_long$variable, levels = c("Hydro", "Biofuel", "Geothermal", "Solar"))
    ggplot(rel_years_long, aes(x=Year, y=value, fill=variable)) + 
      geom_area() +
      #Using different hues to demonstrate categorical nature of source
      scale_fill_brewer(palette="Accent") +
      labs(title=paste("Renewable Energy Production from 1990 to", input$year, sep=" "),
           x = "Year",
           y = "Renewable Energy Production (TWh)"
      ) +
      theme(legend.position = "right") +
      guides(fill=guide_legend(title="Renewable Energy Source"))
  })
    
  output$scatterfull <- renderPlot({
    # select China so we can highlight it in the plot
    china <- filter(con_prod_country, Country == "China")
    ggplot(data=con_prod_country_no, aes( x=Consumption, y=total)) +
      geom_point(alpha=0.3) +
      geom_point(data = china, aes(x=Consumption, y=total), color = 'red') +
      labs(
        title="Comparison of total energy consumption and renewable energy production in 2017",
        x = "Total Energy Consumption (TWh)", 
        y = "Renewable Energy Production (TWh)"
      )
    })
    
  # scatter plot of total energy consumption and renewable energy production (all countries)
  output$scatter_info <- renderText({
    point <- nearPoints(con_prod_country, input$scatter_click, threshold = 10, maxpoints = 1)
    if(nrow(point) == 0) return(NULL)
    paste0("Country name: ", point$Country)
  })
  
  # scatter plot of total energy consumption and renewable energy production (no outliers)
  output$no_outliers <- renderPlot({
    ggplot(con_prod_country_no, aes(x=Consumption, y=total)) +
      geom_point() +
      labs(
        title=paste("Comparison of total energy consumption and renewable energy production in 2017"),
        x = "Total Energy Consumption (TWh)", 
        y = "Renewable Energy Production (TWh)")
    })
    
    #click to display name of country (no outliers)
  output$no_info <- renderText({
    point <- nearPoints(con_prod_country, input$no_click, threshold = 10, maxpoints = 1)
    if(nrow(point) == 0) return(NULL)
    paste0("Country name: ", point$Country)
  })
}

shinyApp(ui = ui, server = server)
```